/**
 * Demo Data Generator for Dashboard
 *
 * Generates realistic demo data for showcasing dashboard features
 */

import { Product } from '../index';

export interface DemoProduct extends Omit<Product, 'createdAt' | 'updatedAt'> {
  createdAt: string;
  updatedAt: string;
}

export const demoProducts: DemoProduct[] = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    name: 'Wireless Earbuds Pro Max',
    description: 'Premium wireless earbuds with active noise cancellation and 30-hour battery life',
    category: 'Electronics',
    price: 149.99,
    currency: 'USD',
    brand: 'AudioTech',
    rating: 4.8,
    reviewCount: 2547,
    tags: ['wireless', 'bluetooth', 'noise-cancelling', 'premium'],
    source: 'Amazon',
    sourceUrl: 'https://example.com/product1',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    name: 'Smart Watch Series 5',
    description: 'Advanced fitness tracking with heart rate monitoring and GPS',
    category: 'Electronics',
    price: 399.99,
    currency: 'USD',
    brand: 'TechPro',
    rating: 4.6,
    reviewCount: 1823,
    tags: ['smartwatch', 'fitness', 'gps', 'health'],
    source: 'Best Buy',
    sourceUrl: 'https://example.com/product2',
    createdAt: new Date('2024-01-14').toISOString(),
    updatedAt: new Date('2024-01-14').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    name: 'Ultra HD 4K Monitor 32"',
    description: '32-inch 4K monitor with HDR support and 144Hz refresh rate',
    category: 'Electronics',
    price: 549.99,
    currency: 'USD',
    brand: 'ViewMaster',
    rating: 4.7,
    reviewCount: 956,
    tags: ['monitor', '4k', 'gaming', 'hdr'],
    source: 'Newegg',
    sourceUrl: 'https://example.com/product3',
    createdAt: new Date('2024-01-13').toISOString(),
    updatedAt: new Date('2024-01-13').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    name: 'Gaming Keyboard RGB Mechanical',
    description: 'Mechanical gaming keyboard with customizable RGB lighting and macro keys',
    category: 'Electronics',
    price: 89.99,
    currency: 'USD',
    brand: 'GamePro',
    rating: 4.5,
    reviewCount: 1432,
    tags: ['gaming', 'keyboard', 'rgb', 'mechanical'],
    source: 'Amazon',
    sourceUrl: 'https://example.com/product4',
    createdAt: new Date('2024-01-12').toISOString(),
    updatedAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440005',
    name: 'Noise Cancelling Headphones Studio',
    description: 'Professional studio-grade headphones with superior noise cancellation',
    category: 'Electronics',
    price: 279.99,
    currency: 'USD',
    brand: 'AudioTech',
    rating: 4.9,
    reviewCount: 3241,
    tags: ['headphones', 'noise-cancelling', 'professional', 'audio'],
    source: 'B&H Photo',
    sourceUrl: 'https://example.com/product5',
    createdAt: new Date('2024-01-11').toISOString(),
    updatedAt: new Date('2024-01-11').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440006',
    name: 'Designer Backpack Leather',
    description: 'Premium leather backpack with laptop compartment and USB charging port',
    category: 'Fashion',
    price: 79.99,
    currency: 'USD',
    brand: 'UrbanStyle',
    rating: 4.4,
    reviewCount: 687,
    tags: ['backpack', 'leather', 'fashion', 'laptop'],
    source: 'Nordstrom',
    sourceUrl: 'https://example.com/product6',
    createdAt: new Date('2024-01-10').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440007',
    name: 'Running Shoes Elite Performance',
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh',
    category: 'Sports',
    price: 129.99,
    currency: 'USD',
    brand: 'SportMax',
    rating: 4.6,
    reviewCount: 1523,
    tags: ['running', 'shoes', 'sports', 'fitness'],
    source: "Dick's Sporting Goods",
    sourceUrl: 'https://example.com/product7',
    createdAt: new Date('2024-01-09').toISOString(),
    updatedAt: new Date('2024-01-09').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440008',
    name: 'Coffee Maker Deluxe Programmable',
    description: 'Smart coffee maker with programmable settings and thermal carafe',
    category: 'Home & Garden',
    price: 159.99,
    currency: 'USD',
    brand: 'BrewMaster',
    rating: 4.5,
    reviewCount: 892,
    tags: ['coffee', 'kitchen', 'appliance', 'smart'],
    source: 'Target',
    sourceUrl: 'https://example.com/product8',
    createdAt: new Date('2024-01-08').toISOString(),
    updatedAt: new Date('2024-01-08').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440009',
    name: 'Yoga Mat Premium Non-Slip',
    description: 'Extra-thick yoga mat with non-slip surface and carrying strap',
    category: 'Sports',
    price: 39.99,
    currency: 'USD',
    brand: 'ZenFit',
    rating: 4.7,
    reviewCount: 2134,
    tags: ['yoga', 'fitness', 'mat', 'exercise'],
    source: 'Amazon',
    sourceUrl: 'https://example.com/product9',
    createdAt: new Date('2024-01-07').toISOString(),
    updatedAt: new Date('2024-01-07').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440010',
    name: 'Air Fryer XXL Digital',
    description: 'Large capacity air fryer with digital controls and 8 preset programs',
    category: 'Home & Garden',
    price: 119.99,
    currency: 'USD',
    brand: 'CookPro',
    rating: 4.6,
    reviewCount: 1678,
    tags: ['airfryer', 'kitchen', 'cooking', 'appliance'],
    source: 'Walmart',
    sourceUrl: 'https://example.com/product10',
    createdAt: new Date('2024-01-06').toISOString(),
    updatedAt: new Date('2024-01-06').toISOString(),
  },
];

export const demoStats = {
  totalProducts: 15234,
  totalCategories: 24,
  totalSources: 8,
  avgSentiment: 7.8,
  categories: [
    'Electronics',
    'Fashion',
    'Home & Garden',
    'Sports',
    'Books',
    'Toys',
    'Beauty',
    'Automotive',
    'Health',
    'Office',
  ],
  sources: [
    'Amazon',
    'eBay',
    'Walmart',
    'Target',
    'Best Buy',
    'Newegg',
    'Nordstrom',
    'B&H Photo',
  ],
};

export const demoTrendAnalysis = {
  Electronics: {
    category: 'Electronics',
    trendingProducts: demoProducts.filter(p => p.category === 'Electronics').slice(0, 5),
    priceMovement: 'up' as const,
    averagePrice: 272.99,
    totalProducts: 4523,
  },
  Fashion: {
    category: 'Fashion',
    trendingProducts: demoProducts.filter(p => p.category === 'Fashion'),
    priceMovement: 'stable' as const,
    averagePrice: 79.99,
    totalProducts: 3214,
  },
  Sports: {
    category: 'Sports',
    trendingProducts: demoProducts.filter(p => p.category === 'Sports'),
    priceMovement: 'down' as const,
    averagePrice: 84.99,
    totalProducts: 2156,
  },
};

export const demoSentiment = {
  positive: 68,
  neutral: 24,
  negative: 8,
};

export const demoRiskData = [
  { name: 'Price Volatility', level: 'low' as const, value: 25 },
  { name: 'Stock Shortage', level: 'medium' as const, value: 55 },
  { name: 'Competition Risk', level: 'high' as const, value: 75 },
  { name: 'Demand Fluctuation', level: 'medium' as const, value: 45 },
];

export const demoIngestionData = [
  {
    name: 'Amazon API',
    lastSync: '2 minutes ago',
    records: 5234,
    status: 'active' as const,
  },
  {
    name: 'eBay Feed',
    lastSync: '15 minutes ago',
    records: 3421,
    status: 'active' as const,
  },
  {
    name: 'Walmart CSV',
    lastSync: '1 hour ago',
    records: 2156,
    status: 'pending' as const,
  },
  {
    name: 'Target API',
    lastSync: '3 hours ago',
    records: 1823,
    status: 'active' as const,
  },
];

export const demoPriceHistory = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
  averagePrice: [245, 259, 280, 281, 256, 255],
  competitorPrice: [265, 279, 295, 299, 276, 275],
};
